### ISSUE TITLE
颜色渐变

### ISSUE THREAD

**Issue by huhu2008** [ldoublem/AlpayRing#1]
像芝麻分那样的建怎么搞？

**Comment by ldoublem** [comment]
ArgbEvaluator evaluator = new ArgbEvaluator();  
color = (Integer) evaluator.evaluate(f, startColor, endColor);

**Comment by huhu2008** [comment]
谢谢回答 我没说清楚 我看芝麻信用他的整个页面 从上到下也是渐变 不知道这么做

**Comment by ldoublem** [comment]
那你可以试试Shader
